name: Deploy my site to GitHub Pages

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Build & Export Next.js
              run: pnpm build

            - name: Fix GitHub Pages Issues
              run: touch ./out/.nojekyll

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.9
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: gh-pages # Deploy branch
                  folder: out # Next.js export folder
